### ISSUE TITLE
Signature comparison isn't secure against Timing Attacks

### ISSUE THREAD

**Issue by MunifTanjim** [lagden/signature#2]
https://github.com/lagden/signature/blob/56ee75fb8c85345aff2fcfad683783d8a77004d0/index.js#L16

This comparison should be secure against timing attacks.

### References

- [Timing Attacks against String Comparison](https://thisdata.com/blog/timing-attacks-against-string-comparison/)

> Timing attacks are a way of learning information about something by measuring the time it takes to respond to different queries. When a response is faster or slower based on what you send it, the algorithm is leaking information about what two values are being compared.

- [Securing your webhooks | GitHub ](https://developer.github.com/webhooks/securing/#validating-payloads-from-github)

> Using a plain `==` operator is **not advised**. A method like `secure_compare` performs a "constant time" string comparison, which renders it safe from certain timing attacks against regular equality operators.

- [Compare signatures | Stripe](https://stripe.com/docs/webhooks/signatures#compare-signatures)

> To protect against timing attacks, use a constant-time string comparison to compare the expected signature to each of the received signatures.

**Comment by lagden** [comment]
@MunifTanjim 

Tks! ;)
